name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop running process
        run: |
          pkill -f mainStockPage.py || true
          sleep 5

      - name: Pull latest changes
        run: |
          cd /home/${{ secrets.PI_USERNAME }}/StockAi
          git pull origin main

      - name: Restart application
        run: |
          sudo reboot