name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main   # or 'main', whichever branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/${{ secrets.PI_USERNAME }}/your-project
            git pull origin master
            # (Optional) Restart the app service if you're using a systemd service:
            # sudo systemctl restart stockapp.service
