name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/${{ secrets.PI_USERNAME }}/StockAi
            git pull origin main
            # Kill any running instance of your app (change the pattern if needed)
            pkill -f mainStockPage.py || true
            sleep 5
            # Restart the app with the proper environment
            env DISPLAY=:0 /home/${{ secrets.PI_USERNAME }}/StockAi/venv/bin/python /home/${{ secrets.PI_USERNAME }}/StockAi/mainStockPage.py &
