name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main   # Adjust based on your branch name

jobs:
  deploy:
    runs-on: self-hosted  # Since you have the Pi as a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        run: |
          cd /home/coleweber/StockAi
          git pull origin main
          pkill -f mainStockPage.py  # Kill the existing process if running
          sleep 2  # Small delay to ensure process stops
          nohup env DISPLAY=:0 /home/coleweber/StockAi/venv/bin/python /home/coleweber/StockAi/mainStockPage.py >> /home/coleweber/reboot.log 2>&1 &
